### ISSUE TITLE
FleetAPI: getVehicles() → Error Domain=TeslaError Code=412

### ISSUE THREAD

**Issue by Krillle** [jonasman/TeslaSwift#166]
Using TeslaSwift 9.1.0. I have changed my code to Fleet API. Same code was working well before with Owners API.

The FleetAPI app registration is working fine. My app is getting approval for access to my Tesla Account. I can see my app in my Tesla account under **Third Party Apps** and it has access rights to **Vehicle Information** and **Vehicle Commands**

But I trying to get the list of my vehicles by `Tesla.api.getVehicles()`, I am getting `Error Domain=TeslaError Code=412`. I did not touch the code for getting the vehicles. Has the TeslaSwift API been changed here?

This is the relevant part of my code. It is a straight forward copy of the example in [TeslaSwiftDemo](https://github.com/jonasman/TeslaSwift/tree/master/TeslaSwiftDemo):

```
struct Tesla {
   static var api = TeslaSwift(teslaAPI: TeslaAPI.fleetAPI(region: .europeMiddleEastAfrica, clientID: clientID, clientSecret: clientSecret, redirectURI: redirectURI))
}

[...]

let (webloginViewController, result) = Tesla.api.authenticateWeb()   // ← This is successful. Tokes is issued and App listed as authorized in my Tesla account.

Task { @MainActor in
   _ = try await result()
   guard Tesla.api.isAuthenticated else { return }
   Task { @MainActor in
      do {
         let vehicles = try await Tesla.api.getVehicles()   // ← This fails with Error Domain=TeslaError Code=412
      } catch {
         print("Authentication: Requesting vehicles failed,", error)
      }
   }
}
```

I would be grateful for some advice, if this problem is in the TeslaSwift API or on my side .

**Comment by jonasman** [comment]
Just tried here and it worked.
Can you see what is the actual error from the api?
Check if you are using all the tokens correctly

Sent from my iPhone

On 1 Feb 2024, at 13:38, Christian Wegerhoff ***@***.***> wrote:

﻿

Using TeslaSwift 9.1.0. I have changed my code to Fleet API. Same code was working well before with Owners API.

The FleetAPI app registration is working fine. My app is getting approval for access to my Tesla Account. I can see my app in my Tesla account under Third Party Apps and it has access rights to Vehicle Information and Vehicle Commands

But I trying to get the list of my vehicles by Tesla.api.getVehicles(), I am getting Error Domain=TeslaError Code=412. I did not touch the code for getting the vehicles. Has the TeslaSwift API been changed here?

This is the relevant part of my code. It is a straight forward copy of the example in TeslaSwiftDemo<https://github.com/jonasman/TeslaSwift/tree/master/TeslaSwiftDemo>:

struct Tesla {
   static var api = TeslaSwift(teslaAPI: TeslaAPI.fleetAPI(region: .europeMiddleEastAfrica, clientID: clientID, clientSecret: clientSecret, redirectURI: redirectURI))
}

[...]

let (webloginViewController, result) = Tesla.api.authenticateWeb()   // ← This is successful. Tokes is issued and App listed as authorized in my Tesla account.

Task { @MainActor in
   _ = try await result()
   guard Tesla.api.isAuthenticated else { return }
   Task { @MainActor in
      do {
         let vehicles = try await Tesla.api.getVehicles()   // ← This fails with Error Domain=TeslaError Code=412
      } catch {
         print("Authentication: Requesting vehicles failed,", error)
      }
   }
}


I would be grateful for some advice, if this problem is in the TeslaSwift API or on my side .

**Comment by Krillle** [comment]
Which thank you for coming back to me. 

Which Tesps Api Scopes do I need for `getVehicles()`, only **Vehicle Information**, or **Profile Information** as well?

What has changed using the tokens correctly? I did not change my code here, yet. What do I dded to change to adopt to FleetAPI?

**Comment by Krillle** [comment]
@jonasman Thank you for coming back to me. 

Which Tesps Api Scopes do I need for `getVehicles()`, only **Vehicle Information**, or **Profile Information** as well?

What has changed using the tokens correctly? I did not change my code here, yet. What do I dded to change to adopt to FleetAPI?

**Comment by Krillle** [comment]
Solved: These steps have been missing: 

C — Generate the partner authentication token
D — Register the app using a authentication token

Here at [Medium](https://shankar-k.medium.com/tesla-developer-api-guide-account-setup-app-creation-registration-and-third-party-da24aba1bddd) is a very good and detailed guide how to do it.
