### ISSUE TITLE
Flat encoding of VehicleExtended

### ISSUE THREAD

**Issue by heumn** [jonasman/TeslaSwift#39]
I cache the extended vehicle in UserDefaults, but to be able to decode and encode the current version of this class I had to flatten the structure for `VehicleExtended` see: https://github.com/heumn/TeslaSwift/commits/feature/flat_json_encoding

If you don't, you end up with a structure that looks like this after encoding

```
{
  "super" : {
    "backseatToken" : "asdasdasd",
  ...
  },
  "userId" : 123123,
  ... 
}
```

meaning trying to decode this from UserDefaults again, all properties of `VehicleExtended`s superclass, `Vehicle` will be nil.

So I am just wondering if this is a bug or intentional. Why would you want to encode it like that? I could understand it if you wanted to avoid overlapping properties, but that does not seem to be the case here 🤔

**Comment by jonasman** [comment]
This is probably a bug. Superclasses decoding is tricky but encoding i have no tried. Do you have a solution?

**Comment by heumn** [comment]
Also depends on how people are using it. Changing this will clearly break existing logic around archiving. Wondering if anyone else here has any input?

**Comment by jonasman** [comment]
So i made some tests and find out that we cannot extend Vehicle like the lib is doing because:
1) Tesla is sending the extended vehicle in a normal format
2) JSONEncoder encodes super classes with the tag "super" instead of flattening the encoding.

I come up with workaround for the issue in https://github.com/jonasman/TeslaSwift/commit/a0c00c4c7c62752855292e608b98a883b4a91288

**Comment by jonasman** [comment]
Closing as this should fix the problem. Let me know if you still have other issues

**Comment by heumn** [comment]
Awesome 👏
