### ISSUE TITLE
Model Protocol Implementations

### ISSUE THREAD

**Issue by ericlewis** [jonasman/TeslaSwift#57]
A useful feature may be to implement all of the models as protocols, while providing structs still for use. The reasoning for this is that you could more easily build in `CoreData` support and make sure you still match all of the model structures.

**Comment by jonasman** [comment]
Hi, thanks for this PR.

I'm still not fully convinced about this change. If we change the models, and we change them often, it would break your core data easily. So the benefit of reusing the API models are not that much.

From the architectural POV I would not recommend using the API data models as your data storage models because you would be too dependent on the API.

**Comment by jonasman** [comment]
I will reject this change as I think this is not the correct way to implement Model Data. The library should also be independent of 3rd party implementations.
