### ISSUE TITLE
Support for the new "real" oAuth2

### ISSUE THREAD

**Issue by rawmean** [jonasman/TeslaSwift#60]
Tesla app now uses a true oAuth2 protocol. specifically, the user no longer enters their credentials directly to the app; instead the user enters their credentials to a Tesla website directly.

This is the URL that is used to initiate oAuth:
   https://auth.tesla.com/oauth2/v3/authorize?client_id=ownerapi&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fauth.tesla.com%2Fvoid%2Fcallback&locale=en&prompt=login&response_type=code&scope=email&state=xlni7Qb4ON540kwGBopz

The problem is that the redirect_uri is set to "https://auth.tesla.com/void/callback" and changing that will cause http 400 error.

Do you have plans to support the new oAuth2. I'm happy to collaborate.

**Comment by jonasman** [comment]
Hi!

Thanks for the heads up. Any ideas on how to solve the problem?
Maybe we don't care about the callback after we get the token?

I will need to check how the JS library is solving the issue



Sent from my iPhone

On 6. Sep 2020, at 20.35, Ramin <notifications@github.com> wrote:

﻿

Tesla app now uses a true oAuth2 protocol. specifically, the user no longer enters their credentials directly to the app; instead the user enters their credentials to a Tesla website directly.

This is the URL that is used to initiate oAuth:
https://auth.tesla.com/oauth2/v3/authorize?client_id=ownerapi&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fauth.tesla.com%2Fvoid%2Fcallback&locale=en&prompt=login&response_type=code&scope=email&state=xlni7Qb4ON540kwGBopz

The problem is that the redirect_uri is set to "https://auth.tesla.com/void/callback" and changing that will cause http 400 error.

Do you have plans to support the new oAuth2. I'm happy to collaborate.

**Comment by rawmean** [comment]
I have written a simple iOS app which uses "oAuthSwift" to authenticate using the new oAuth endpoint, but the problem is that I cannot send the `redirect_uri` to a scheme that is bound to the app.

It's instructive to look at the exchanges between Tesla app (on Android) and the Tesla server. You can do that using Appetize.io easily.

Which JS library are you referring to?

**Comment by jonasman** [comment]
This js lib: https://tesla-api.timdorr.com/

I just logged out and logged in with the Tesla app and there is no Web login yet. So i don't see any problem in using the new auth and fake the whole thing.

**Comment by rawmean** [comment]
The login screen that you see in Tesla app is this site (it's show in an embedded browser): 
https://auth.tesla.com/oauth2/v3/authorize?client_id=ownerapi&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fauth.tesla.com%2Fvoid%2Fcallback&locale=en&prompt=login&response_type=code&scope=email&state=xlni7Qb4ON540kwGBopz

Yes, the old endpoint for authentication still works and so that TeslaSwift

**Comment by SohrabYY** [comment]
Tesla activate MFA today, do you guys have any update on this?

**Comment by jonasman** [comment]
Im following the progress by the JS api guys.
So far there is no need to take any action as the current apis are still supported and mfa is not enforced on api level even if you enabled mfa on your account.

Hopefully Tesla will officially support third party apps. In that case this lib will support that auth method.

So far we need to wait to see what are the options for the lib.

Sent from my iPhone

On 7. Oct 2020, at 0.24, Sohrab <notifications@github.com> wrote:

﻿

Tesla activate MFA today, do you guys have any update on this?

**Comment by jonasman** [comment]
https://github.com/timdorr/tesla-api/issues/215

**Comment by jonasman** [comment]
oAuth2 with Web authentication is now supported in the master branch.

**Comment by jonasman** [comment]
the code changes also support refresh tokens. Before it was making a new login instead of a refresh.

**Comment by jonasman** [comment]
Revoke tokens is not working for the web login. I don't know why.

**Comment by jonasman** [comment]
MFA is iOS 13 only for now

**Comment by geho2** [comment]
Working Python code without MFA is now available here (see function __tesla_connect): https://github.com/bismuthfoundation/TornadoWallet/blob/c4c902a2fe2d45ec399416baac4eefd39d596418/wallet/crystals/420_tesla/teslaapihandler.py#L219
